apiVersion: 1

datasources:
  - name: telegraf
    type: influxdb
    access: proxy
    database: telegraf
    url: http://influxdb:8086
    basicAuth: false
    user: telegraf
    password: INFLUXDB_DATABASE_PASSWORD

